version: '3'
services:
  music-nginx:
    build:
      context: music/docker/dev
      dockerfile: nginx.docker
    volumes:
      - ./music:/app
    depends_on:
      - music-php-fpm
    ports:
      - "8080:80"
  music-php-fpm:
    build:
      context: music/docker/dev
      dockerfile: php-fpm.docker
    volumes:
      - ./music:/app
    depends_on:
      - music-postgres
      - music-storage
      - music-mailer
  music-php-cli:
    build:
      context: music/docker/dev
      dockerfile: php-cli.docker
    volumes:
      - ./music:/app
      - composer:/root/.composer/cache
    tty: true
    depends_on:
      - music-postgres
      - music-storage
      - music-mailer
  music-postgres:
    image: postgres:11.2-alpine
    volumes:
      - music-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"
  music-storage:
    build:
      context: ./storage/docker/dev
      dockerfile: nginx.docker
    volumes:
      - ./storage:/app
    ports:
      - "8081:80"
  music-storage-ftp:
    image: stilliard/pure-ftpd
    environment:
      FTP_USER_NAME: app
      FTP_USER_PASS: secret
      FTP_USER_HOME: /app
    volumes:
      - ./storage/public:/app
  music-mailer:
    image: mailhog/mailhog
    ports:
      - "8082:8025"
  music-node:
    image: node:11.13-alpine
    volumes:
      - ./music:/app
    working_dir: /app
    tty: true
  music-node-watch:
    image: node:11.13-alpine
    volumes:
      - ./music:/app
    working_dir: /app
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"

volumes:
  music-postgres:
  composer: