parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '11.2'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: -

        types:
            music_artist_id: 'App\Model\Music\Entity\Artist\IdType'
            music_artist_login: 'App\Model\Music\Entity\Artist\LoginType'

            music_song_id: 'App\Model\Music\Entity\Song\IdType'
            music_song_name: 'App\Model\Music\Entity\Song\NameType'
            music_song_status: 'App\Model\Music\Entity\Song\StatusType'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Music:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Music/Entity'
                prefix: 'App\Model\Music\Entity'
                alias: Music