parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '11.2'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: -

        url: '%env(resolve:DATABASE_URL)%'

        types:
            music_genre_id: 'App\Model\Music\Entity\Genre\IdType'
            music_genre_name: 'App\Model\Music\Entity\Genre\NameType'
            music_genre_slug: 'App\Model\Music\Entity\Genre\SlugType'

            music_artist_id: 'App\Model\Music\Entity\Artist\IdType'
            music_artist_login: 'App\Model\Music\Entity\Artist\LoginType'

            music_song_id: 'App\Model\Music\Entity\Song\IdType'
            music_song_name: 'App\Model\Music\Entity\Song\NameType'
            music_song_status: 'App\Model\Music\Entity\Song\StatusType'
            music_song_download_url: 'App\Model\Music\Entity\Song\DownloadUrlType'
            music_song_download_status: 'App\Model\Music\Entity\Song\DownloadStatusType'

            music_album_id: 'App\Model\Music\Entity\Album\IdType'
            music_album_title: 'App\Model\Music\Entity\Album\TitleType'
            music_album_slug: 'App\Model\Music\Entity\Album\SlugType'
            music_album_release_year: 'App\Model\Music\Entity\Album\ReleaseYearType'
            music_album_cover_photo: 'App\Model\Music\Entity\Album\CoverPhotoType'
            music_album_description: 'App\Model\Music\Entity\Album\DescriptionType'
            music_album_status: 'App\Model\Music\Entity\Album\StatusType'
            music_album_type: 'App\Model\Music\Entity\Album\TypeType'

            user_user_id: 'App\Model\User\Entity\User\IdType'
            user_user_login: 'App\Model\User\Entity\User\LoginType'
            user_user_email: 'App\Model\User\Entity\User\EmailType'
            user_user_password: 'App\Model\User\Entity\User\PasswordType'
            user_user_avatar: 'App\Model\User\Entity\User\AvatarType'
            user_user_confirm_token: 'App\Model\User\Entity\User\ConfirmTokenType'
            user_user_status: 'App\Model\User\Entity\User\StatusType'
            user_user_role: 'App\Model\User\Entity\User\RoleType'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Music:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Music/Entity'
                prefix: 'App\Model\Music\Entity'
                alias: Music

            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User