parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Database\Migrations,Model\Music\Entity,Tests,Kernel.php}'

    App\Model\Music\Entity\Song\SongRepository: ~
    App\Model\Music\Entity\Artist\ArtistRepository: ~
    App\Model\User\Entity\User\UserRepository: ~

    App\Http\Controller\:
        resource: '../src/Http/Controller'
        tags: ['controller.service_arguments']

    App\Service\Uploader\FileUploader:
        arguments: ['@default.storage', '%env(STORAGE_BASE_URL)%']

    App\Model\User\UseCase\User\SignUp\ByEmail\Request\Handler:
        arguments:
            $tokenGenerator: '@App\Model\User\Service\ConfirmUuidTokenGenerator'
            $tokenSender: '@App\Model\User\Service\ConfirmEmailTokenSender'
            $hasher: '@App\Model\User\Service\ArgonHasher'

    App\Security\LoginFormAuthenticator:
        arguments:
            $hasher: '@App\Model\User\Service\ArgonHasher'
